name: 'Unique versioning action for maven'
description: 'Unique versioning based on workflows current number'
inputs:
  pom-dir:
    description: 'Path to the directory containing the project'
    required: true
    default: ${{ github.workspace }}

runs:
  using: 'composite'
  steps:
    - run: |
        npm install xml2js
        node index.js ${{ github.workspace }}
      working-directory: ${{ github.action_path }}
      shell: bash